# .prettierrc or .prettierrc.yaml
trailingComma: "all"
tabWidth: 4
semi: true
singleQuote: true

overrides:
  - files: "manifest.json"
    options:
      tabWidth: 4

  - files: "settings.json"
    options:
      tabWidth: 4

  - files: "package.json"
    options:
      tabWidth: 4

  - files: "tsconfig.json"
    options:
      tabWidth: 4

  - files: "*.js"
    options:
      tabWidth: 4
      printWidth: 160

  - files: "*.ts"
    options:
      tabWidth: 4
      printWidth: 160

  - files: "*.tsx"
    options:
      tabWidth: 4
      printWidth: 160

  - files: "*.css"
    options:
      tabWidth: 4
      printWidth: 160

  - files: "*.html"
    options:
      tabWidth: 4
      printWidth: 160

  - files: ".babelrc"
    options:
      tabWidth: 4
      printWidth: 160
